apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-auth
  labels:
    micro: server
    name: micro-auth
  annotations:
    name: "go.micro.auth"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-auth
      micro: server
  template:
    metadata:
      labels:
        name: micro-auth
        micro: server
    spec:
      containers:
      - name: auth
        args:
        - auth
        ports:
        - containerPort: 8000
          name: auth-port