apiVersion: v1
kind: Service
metadata:
  name: micro-auth
  namespace: default
  labels:
    name: micro-auth
    micro: server
spec:
  ports:
  - port: 8010
    protocol: TCP
  selector:
    name: micro-auth
    micro: server
