apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-bot
  labels:
    micro: client
    name: micro-bot
  annotations:
    name: "go.micro.bot"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-bot
      micro: client
  template:
    metadata:
      labels:
        name: micro-bot
        micro: client
    spec:
      containers:
        - name: bot
          command: [
            "/micro",
            "bot",
            "--inputs=slack"
          ]
          env:
          - name: MICRO_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: micro-secrets
                key: slack