apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-broker
  labels:
    micro: server
    name: micro-broker
  annotations:
    name: "go.micro.broker"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-broker
      micro: server
  template:
    metadata:
      labels:
        name: micro-broker
        micro: server
    spec:
      containers:
      - name: broker
        args:
        - broker
        ports:
        - containerPort: 8001
          name: broker-port