apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-config
  labels:
    name: micro-config
    micro: server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-config
      micro: server
  template:
    metadata:
      labels:
        name: micro-config
        micro: server
    spec:
      containers:
      - name: micro-config
        args:
        - broker
        ports:
        - containerPort: 8080
          name: service