apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-debug
  labels:
    micro: server
    name: micro-debug
  annotations:
    name: "go.micro.debug"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-debug
      micro: server
  template:
    metadata:
      labels:
        name: micro-debug
        micro: server
    spec:
      containers:
      - name: micro-debug
        env:
        - name: MICRO_DEBUG_LOG
          value: "service"
        - name: MICRO_DEBUG_WINDOW
          value: "600"
        args:
        - debug