apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-proxy
  labels:
    micro: client
    name: micro-proxy
  annotations:
    name: "go.micro.proxy"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-proxy
      micro: client
  template:
    metadata:
      labels:
        name: micro-proxy
        micro: client
    spec:
      containers:
      - name: proxy
        env:
        - name: MICRO_ACME_HOSTS
          value: 'proxy.m3o.dev'
        args:
        - proxy
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https-port
        - containerPort: 8081
          name: proxy-port
