apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-registry
  labels:
    micro: server
    name: micro-registry
  annotations:
    name: "go.micro.registry"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-registry
      micro: server
  template:
    metadata:
      labels:
        name: micro-registry
        micro: server
    spec:
      containers:
      - name: registry
        args:
        - registry
        ports:
        - containerPort: 8000
          name: registry-port
        image: micro/micro
        imagePullPolicy: Always