apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-router
  labels:
    micro: server
    name: micro-router
  annotations:
    name: "go.micro.router"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-router
      micro: server
  template:
    metadata:
      labels:
        name: micro-router
        micro: server
    spec:
      containers:
      - name: router
        env:
        - name: MICRO_ENABLE_ACME
          value: "true"
        args:
        - router
        ports:
        - containerPort: 8084
          name: router-port