apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-runtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-runtime
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - namespaces
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/logs
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro-runtime
subjects:
- kind: ServiceAccount
  name: micro-runtime
  namespace: default
roleRef:
  kind: ClusterRole
  name: micro-runtime
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-runtime
subjects:
- kind: ServiceAccount
  name: micro-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-runtime
  labels:
    micro: server
    name: micro-runtime
  annotations:
    name: "go.micro.runtime"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-runtime
      micro: server
  template:
    metadata:
      labels:
        name: micro-runtime
        micro: server
    spec:
      serviceAccount: micro-runtime
      serviceAccountName: micro-runtime
      containers:
      - name: runtime
        env:
        - name: MICRO_RUNTIME
          value: "kubernetes"
        - name: MICRO_RUNTIME_PROFILE
          value: "platform"
        - name: MICRO_AUTO_UPDATE
          value: "true"
        args:
        - runtime