apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-store
  labels:
    name: micro-store
    micro: server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-store
      micro: server
  template:
    metadata:
      labels:
        name: micro-store
        micro: server
    spec:
      containers:
      - name: micro-store
        env:
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8002"
        args:
        - store
        ports:
        - containerPort: 8002
          name: service
        image: micro/micro
        imagePullPolicy: Always