apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-web
  labels:
    micro: client
    name: micro-web
  annotations:
    name: "go.micro.web"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-web
      micro: client
  template:
    metadata:
      labels:
        name: micro-web
        micro: client
    spec:
      containers:
      - name: web
        env:
        - name: MICRO_ACME_HOSTS
          value: 'web.m3o.dev'
        args:
        - web
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: web-port
        image: micro/micro
        imagePullPolicy: Always